<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="2" total="3" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="65028" started-at="2024-01-14T15:57:20 IST" finished-at="2024-01-14T15:58:25 IST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="65028" started-at="2024-01-14T15:57:20 IST" finished-at="2024-01-14T15:58:25 IST">
      <class name="insuranceCalculation_Motorcycle.ErrorTests_motorcycle">
        <test-method status="PASS" signature="setupMethod()[pri:0, instance:insuranceCalculation_Motorcycle.ErrorTests_motorcycle@23d2a7e8]" name="setupMethod" is-config="true" duration-ms="55994" started-at="2024-01-14T15:57:20 IST" finished-at="2024-01-14T15:58:16 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupMethod -->
        <test-method status="FAIL" signature="verifyModelDropdownOptions()[pri:0, instance:insuranceCalculation_Motorcycle.ErrorTests_motorcycle@23d2a7e8]" name="verifyModelDropdownOptions" duration-ms="7878" started-at="2024-01-14T15:58:16 IST" finished-at="2024-01-14T15:58:24 IST">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at insuranceCalculation_Motorcycle.ErrorTests_motorcycle.verifyModelDropdownOptions(ErrorTests_motorcycle.java:43)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyModelDropdownOptions -->
        <test-method status="PASS" signature="cleanUp()[pri:0, instance:insuranceCalculation_Motorcycle.ErrorTests_motorcycle@23d2a7e8]" name="cleanUp" is-config="true" duration-ms="960" started-at="2024-01-14T15:58:24 IST" finished-at="2024-01-14T15:58:25 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cleanUp -->
      </class> <!-- insuranceCalculation_Motorcycle.ErrorTests_motorcycle -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
